config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :applicants
  resources :donations


  get 'home/index'

  authenticated do
    root 'applicants#index'
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

  def new
    @applicant = Applicant.new
  end
  
  def index
    @applicants = Applicant.all
  end

  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.save
      redirect_to root_path
    else
      redirect_to root_path
    end

  end


  def applicant_params
    params.require(:applicant).permit!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
    def new
    end
  
    def index
      @donations = Donation.all
    end
  
 
  
  
    
  
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @applicant = Applicant.new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
     @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to root_path
    else
      render :action => 'new'
    end
  end


  def user_params
    params.require(:user).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applicants/_applicant_row.html.erb
<tr >
  <td><%= link_to applicant.id, edit_applicant_path(applicant.id) %></td>
  <td><%= applicant.name %></td>
  <td><%= applicant.surname %></td>
  <td><%= applicant.city %></td>
  <td><%= applicant.address %></td>
  <td><%= applicant.telephone %></td>
  <td><%= applicant.email %></td>
  <td><%= applicant.total_members %></td>
  <td><%= applicant.incomings %></td>
  <td><%= applicant.description %></td>
</tr>

app/views/applicants/index.html.erb
<div style="border: 0px solid red; margin-top: 20px; margin-bottom: 20px;">
  <%= link_to "New Application", new_applicant_path, class: 'btn btn-primary btn-lg', style: 'border-radius: 5px;' %>
</div>

<table class="table table-striped" style="font-size: 16px;">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Surname</th>
      <th>City</th>
      <th>Address</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Total Members</th>
      <th>Incoming</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'applicant_row', collection: @applicants, as: 'applicant' %>
  </tbody>
</table>

app/views/applicants/new.html.erb
<h1>NEW APPLICATION</h1>
    
<%= form_for @applicant do |f| %>
    <div class="row" style="font-size: 16px;">    
      <div class="col-md-6 mb-3">
        <%= f.label :"Emri", for: "firstName" %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="col-md-6 mb-3">
        <%= f.label :"Mbiemri", for: "surName" %>
        <%= f.text_field :surname, class: "form-control", required: true %>
        <div class="invalid-feedback">
          Valid last name is required.
        </div>
      </div>
    </div>
    <div class="mb-3">
      <%= f.label :"Email", for: "email" %>
      <span class="text-muted"> (Optional)</span>
      <%= f.text_field :email, class: "form-control", placeholder: "you@example.com", type: "email" %>
    </div>
    <div class="mb-3">
      <%= f.label :Qyteti, for: "city" %>
      <%= f.text_field :city, class: "form-control", placeholder: "Debar", required: true %>
    </div>
    <div class="mb-3">
      <%= f.label :Adresa, for: "address" %>
      <%= f.text_field :address, class: "form-control", placeholder: "1234 Main St", required: true %>
    </div>
    <div class="mb-3">
      <%= f.label :"Kontakt telefoni", for: "telephone" %>
      <%= f.text_field :telephone, class: "form-control", placeholder: "+389xx-xxx-xxx", required: true %>
    </div>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= f.label :"Numbri i antareve", for: "total_members" %>:
        <%= f.select(:total_members, ['2', '3', '4', '5', '6', '7', '8'], {}, { :class => 'custom-select d-block w-100', :required => true }) %>
      </div>

      <div class="col-md-6 mb-3">
        <%= f.label :"Te ardhurat mujore", for: "incomings" %>
        <%= f.text_field :incomings, class: "form-control", required: true %>
      </div>
    </div>
    <div class="mb-3">
      <%= f.label :"Pershkrim", for: "description" %>
      <%= f.text_area :description, size: "20x10", class: "form-control", placeholder: "Describe your problem here..", required: true %>
    </div>
    <hr class="mb-4">
    <div class="text-center">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>

app/views/donations/new.html.erb
<header class="masthead" >
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container" style="border: 0px solid red;">
    <%= link_to "Shoqata Atdhetare Dibra", root_path, class: 'navbar-brand js-scroll-trigger', style: 'font-size: 20px;' %>
    </div>
   
    <div class="container">
        <h1> Comming Soon .. </h1>
    </div>
  </nav>
</header>

app/views/home/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top" style="font-size: 20px;">Shoqata Atdhetare Dibra</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path %>
        </li>
      </ul>
    </div>

    <%= link_to "DONATE", new_donation_path, class: 'btn btn-primary btn-lg', style: 'border-radius: 5px;' %>



  </div>
</nav>

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col-lg-7 my-auto">
        <div class="header-content mx-auto">
          <h1 class="mb-5">Mirësevini në faqen kryesore të Shoqatës Atdhetare Dibra - Dega e Bamirësis</h1>
          <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Applikoni me Poshte!</a>
        </div>
      </div>
      <div class="col-lg-5 my-auto">
        <div class="device-container">
          <div class="device-mockup iphone6_plus portrait white">
            <div class="device">
              <div class="screen">
                <img src="img/donate.jpg" class="img-fluid" alt="">
              </div>
              <div class="button">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<section class="download bg-primary text-center" id="download">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h2 class="section-heading">Ju lutemi mbusheni formen me poshte!</h2>
        <p>Ju lutem mbushni te gjitha detalet me poshte!</p>
        <div class="col-md-12 offset-md-0">
      
          <%= form_for @applicant do |f| %>
            <div class="row" style="font-size: 16px;">    
              <div class="col-md-6 mb-3">
                <%= f.label :"Emri", for: "firstName" %>
                <%= f.text_field :name, class: "form-control", required: true %>
              </div>
              <div class="col-md-6 mb-3">
                <%= f.label :"Mbiemri", for: "surName" %>
                <%= f.text_field :surname, class: "form-control", required: true %>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :"Email", for: "email" %>
              <span class="text-muted"> (Optional)</span>
              <%= f.text_field :email, class: "form-control", placeholder: "you@example.com", type: "email" %>
            </div>
            <div class="mb-3">
              <%= f.label :Qyteti, for: "city" %>
              <%= f.text_field :city, class: "form-control", placeholder: "Debar", required: true %>
            </div>
            <div class="mb-3">
              <%= f.label :Adresa, for: "address" %>
              <%= f.text_field :address, class: "form-control", placeholder: "1234 Main St", required: true %>
            </div>
            <div class="mb-3">
              <%= f.label :"Kontakt telefoni", for: "telephone" %>
              <%= f.text_field :telephone, class: "form-control", placeholder: "+389xx-xxx-xxx", required: true %>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <%= f.label :"Numbri i antareve", for: "total_members" %>:
                <%= f.select(:total_members, ['2', '3', '4', '5', '6', '7', '8'], {}, { :class => 'custom-select d-block w-100', :required => true }) %>
              </div>

              <div class="col-md-6 mb-3">
                <%= f.label :"Te ardhurat mujore", for: "incomings" %>
                <%= f.text_field :incomings, class: "form-control", required: true %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :"Pershkrim", for: "description" %>
              <%= f.text_area :description, size: "20x10", class: "form-control", placeholder: "Describe your problem here..", required: true %>
            </div>
            <hr class="mb-4">
            <div class="text-center">
              <%= f.submit class: "btn btn-primary btn-lg" %>
            </div>
          <% end %>
        </div>  
      </div>
    </div>    
  </div>
</section>

<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DibraSHAD</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="vendor/simple-line-icons/css/simple-line-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="device-mockups/device-mockups.min.css">

    <!-- Custom styles for this template -->
    <link href="css/new-age.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <% if user_signed_in? %>
      <div style="display: flex;
                  font-size: 18px; 
                  background-color: #D7DBDD; 
                  height: 75px;     
                  padding: 5px 50px;">
       
        <div style="width: 80%;">
          Logged in as <strong style="color: #E74C3C;"><%= current_user.email %></strong>
        </div>

       

        <div style="text-align:right; width: 20%;">
          <span class="glyphicon glyphicon-user"></span>
          <%= link_to 'My Account', edit_user_registration_path, :style=> 'color: #E74C3C; margin-right: 20px;', :class => 'navbar-link' %>


          <span class="glyphicon glyphicon-user"></span>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :style=> 'color: #E74C3C', :class => 'navbar-link'  %>
        </div>
      </div>
      
      <div style="
                  width: 20%;
                  height: auto;
                  border: 0px solid red;
                  padding: 20px 20px;
                  float: left;
                  "> 
         
        <div style="border: 1px solid #808B96; margin-bottom: 10px; border-radius: 4px; font-size: 18px; padding: 10px 20px;">
          <span style="margin-right: 10px;" class="glyphicon glyphicon-user"></span>
          <%= link_to 'Applications List', applicants_path, :class => 'navbar-link' %>
        </div>

        <div style="border: 1px solid #808B96; margin-bottom: 10px; border-radius: 4px; font-size: 18px; padding: 10px 20px;">
          <span style="margin-right: 10px;" class="glyphicon glyphicon-record"></span>
          <%= link_to 'Users List', users_path, :class => 'navbar-link' %>
        </div>

        <div style="border: 1px solid #808B96; margin-bottom: 10px; border-radius: 4px; font-size: 18px; padding: 10px 20px;
        background-color: #566573; ">
          <span style="margin-right: 10px;" class="glyphicon glyphicon-cog"></span>
          <%= link_to 'Settings', users_path, :class => 'navbar-link' %>
        </div>

      </div>

      <div style="border: 0px solid red; width: 79%; float: left;">
        <%= yield %>
      </div>

    <% else %>
      
      <%= yield %>
      
    <% end %>



    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/new-age.min.js"></script>

  
  </body>

  </html>

app/views/layouts/devise1.html.erb
<style>
    body {background-color: powderblue;}
    h1   {color: blue;}
    p    {color: red;}
</style>

app/views/users/_user_row.html.erb
<tr >
  <td><%= link_to user.id, edit_user_path(user.id) %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/index.html.erb
<div style="border: 0px solid red; margin-top: 20px; margin-bottom: 20px;">
  <%= link_to "New User", new_user_path, class: 'btn btn-primary btn-lg', style: 'border-radius: 5px;' %>

</div>


<table class="table table-striped" style="font-size: 16px;">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'user_row', collection: @users, as: 'user' %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_for @user do |f| %>

    <div class="row" style="font-size: 16px;">    
        <div class="col-md-6">
            <%= f.label :"Email", for: "email" %>
            <%= f.text_field :email, class: "form-control", required: true %>
        </div>
    </div>

    <div class="row" style="font-size: 16px;">    
        <div class="col-md-6">
            <%= f.label :"Password", for: "password" %>
            <%= f.password_field :password, class: "form-control", required: true %>
        </div>
    </div>
 
    <br />
    <div class="text-left">
        <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>

  <% end %>